### ISSUE TITLE
Error: pandoc document conversion failed with error 67

### ISSUE THREAD

**Issue by MahreenAthar** [ramnathv/rcstatebin#10]
Hi I receive this error when i try to fetch a css file. Gives this error:
![capture](https://user-images.githubusercontent.com/39671939/43356640-e185b484-928d-11e8-85bc-92be5cb77d10.PNG)
This is the YAML code:
```
title: "DataScience: The Upcoming Revolution"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    css: C:\Users\Mahreen\Documents\DataScience_Project
````
